### ISSUE TITLE
Awaiting Your Response mod dashboard tab should display resolved tickets

### ISSUE THREAD

**Issue by sdavis2702** [easydigitaldownloads/EDD-bbPress-Support#43]
I saaaaiiid, Awaiting Your Response mod dashboard tab should display resolved tickets! Don't you listen?

**Comment by pippinsplugins** [comment]
Nope, never listen. :D

**Comment by sdavis2702** [comment]
:stuck_out_tongue_closed_eyes:

No real way to test this on dev. Push to master and deploy?

**Comment by pippinsplugins** [comment]
yes.

**Comment by sdavis2702** [comment]
Lovely.
